### ISSUE TITLE
Facing runtime issue with code.

### ISSUE THREAD

**Issue by mitulptridhyatech** [seatsio/seatsio-react#11]
Only Imported library. 
`import { SeatsioSeatingChart } from '@seatsio/seatsio-react'

`

```
ERROR
index.js:1 Uncaught ReferenceError: regeneratorRuntime is not defined
    at index.js:1
    at Object.<anonymous> (index.js:1)
    at r (index.js:1)
    at Object.<anonymous> (index.js:1)
    at r (index.js:1)
    at Object.<anonymous> (index.js:1)
    at r (index.js:1)
    at index.js:1
    at Object.<anonymous> (index.js:1)
    at __webpack_require__ (bootstrap d69aea1ac92ef17c77e4:555)

```

**Comment by nahue** [comment]
Hi! im afraid i cannot do much for you unless you share a little about your build chain.. it seems that you're using webpack, with babel perhaps? if so.. you might want to try this https://babeljs.io/docs/en/babel-polyfill

Please let us know if that works

**Comment by mitul69** [comment]
Hi, 
I am using .env 
not using webpack for the build chain. 
I have installed "npm install --save @babel/polyfill" but still same issue

**Comment by mitul69** [comment]
Found the solutions 
Install babel-polyfill
And import before the module import like bellow 

```
import 'babel-polyfill';
import { SeatsioSeatingChart } from '@seatsio/seatsio-react'
```
