### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by ges134** [seatsio/seatsio-react#12]
Hi! I was looking at this package and how I could integrate it to my react project written in typescript. I can't seem to find any typescript support or any typing packages (`@types/`). 

Currently, in order to integrate it, I have to put the follwing in my files:
```
// eslint-disable-next-line
// @ts-ignore
```

**Comment by ges134** [comment]
I accidentally pressed enter too fast. Here's the updated version.

**Comment by mroloux** [comment]
Hi,

You're right, unfortunately: at this point, we don't provide any TypeScript interfaces or classes. That might change in the future, but certainly not in the short term.

So you'll either have to go with @ts-ignore, or send us a PR with the TypeScript definitions.

Does that make sense?
