### ISSUE TITLE
Places Prompt API 

### ISSUE THREAD

**Issue by riungemaina** [seatsio/seatsio-react#179]
Hi,

I'm trying to us the places prompt API released recently https://docs.seats.io/docs/renderer/prompts-api
I have the example here https://jsfiddle.net/seatsio/d0aj6zug/
but even after upgrading to v.14.9.0 I dont think I have the places prompt API. 
Has it been added to the react package?

**Comment by PabloNeirotti** [comment]
As discussed via support, all the latest features are present in Seats.io React, which is just a wrapper and does not need updating to receive new updates from Seats.io - just leaving this here for anyone else that stumbles upon this issue.

**Comment by riungemaina** [comment]
Hi could you look this over and let me know what I may be doing wrong. 
https://codesandbox.io/p/sandbox/seats-prompts-api-dsrl85?file=%2Fsrc%2FApp.js%3A21%2C1

**Comment by mroloux** [comment]
You'll need to implement `onTicketTypePrompt` instead of `onPlacesPrompt` (https://docs.seats.io/docs/renderer/prompts-api/onTicketTypePrompt)

**Comment by PabloNeirotti** [comment]
What is the issue you experience with your code?
