### ISSUE TITLE
ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by alejandrocfc** [seatsio/seatsio-react#4]
Used seatsio-react as a README said but when is compiled throw:

ReferenceError: regeneratorRuntime is not defined
(anonymous function)
...project/node_modules/@seatsio/seatsio-react/build/index.

**Comment by mroloux** [comment]
Hi, are you using v6 of seatsio-react?

Could you check if the "regenerator-runtime" package is present in the node_modules directory?

**Comment by alejandrocfc** [comment]
Fixed, worked with react-scripts 2.0.*+
