### ISSUE TITLE
Getting SCRIPT1002: Syntax error in Internet Explorer 11 

### ISSUE THREAD

**Issue by nareshrakholiya** [seatsio/seatsio-react#5]
Hi,
We recently integrated seats.io in our react webapp and it seems to be breaking in Internet Explorer 11. Please find attached screenshots for reference. note that all other components are working and following are node and npm versions.
Node - >=10
NPM - >=3.10

![image](https://user-images.githubusercontent.com/53314179/61899042-41e3fa80-af38-11e9-901a-d15b15a2e155.png)

![image](https://user-images.githubusercontent.com/53314179/61899088-588a5180-af38-11e9-8d44-daa5d77f9a4c.png)

**Comment by JKazarian** [comment]
Same issue for me.

**Comment by nareshrakholiya** [comment]
hi, is there any update on this? this is causing issues in our production environment.

**Comment by bverbeken** [comment]
Hi, we have added this to our list and will get back to you asap. 

In the meantime, it would help if you could create a jsfiddle reproducing the problem. 

Thanks!

**Comment by nareshrakholiya** [comment]
hi @bverbeken sure I will create jsfiddle and share here.

**Comment by nahue** [comment]
As discussed on intercom, i'm closing this issue. Create React App does not support IE11 out of the box..  but it can be added using the react-app-polyfill package.
