### ISSUE TITLE
Seatsio  selectedObjects not working

### ISSUE THREAD

**Issue by PpyMohan** [seatsio/seatsio-react#90]
`<SeatsioSeatingChart
                    workspaceKey={publicKey}
                    event={event}      
                    selectedObjects={listOfSelectedSeats}
                    pricing={categoryPrice}
                    unavailableCategories={[]}
                    priceFormatter={(price: any) => "$" + price}
                    region="eu"
                    // session= {'continue'}
                    onObjectSelected={(e: any) => onSeatSelect(e)}
                    onObjectDeselected={(e: any) => onSeatDeSelect(e)}
                />`

Above mentioned code i am using to render seatmap it's loading event i am able to select seats and on seat selection i stored all selected seats in one variable. if i come from another page to seatmap page layout should show previously selected seats but it's not working like that

**Comment by mroloux** [comment]
Hi,

There's no need to pass in `selectedObjects`. I would just remove that parameter.

If you specify `session='continue'`, the chart will automatically re-select seats that were previously selected.

**Comment by PpyMohan** [comment]
Thanks Mroloux it's working

**Comment by PpyMohan** [comment]
session= {'continue'}
after adding session it worked yesterday. morning i checked first time it worked if open next time selected seats are not showing.  
![image](https://user-images.githubusercontent.com/25381060/234505747-e92d6cee-4445-41ee-93ab-0346c72758d0.png)

**Comment by mroloux** [comment]
I checked, and you're on a pretty old seats.io account. For those accounts, we don't show a dialog to the user when his hold token expires - and an option to start a new session.

I've now enabled that feature on your (development) account. Please let me know if I should do the same on production.

**Comment by PpyMohan** [comment]
Thanks
