### ISSUE TITLE
How to deselect selected seats progrmatically

### ISSUE THREAD

**Issue by PpyMohan** [seatsio/seatsio-react#91]
On Seat selection we have some conditions to validate ticket type. and there is a sutituation to deselect ticket. i didn't get option for this

`    <SeatsioSeatingChart

                    workspaceKey={publicKey}

                    event={event}      

                    selectedObjects={listOfSelectedSeats}

                    tooltipInfo={(object: any) => {

                    var tooltipMsg: any[] = [];

                    object.category?.pricing.ticketTypes.map((data: any) => {

                        var ticket_type_title = data.ticketType;

                        toolTipInfo.map((key: tooltipInfo, value: any) => {

                        if (key.type == ticket_type_title) {

                            tooltipMsg.push(key.message);

                        }

                        });

                    });

                    return tooltipMsg.join();

                    }}

                    pricing={categoryPrice}

                    unavailableCategories={[]}

                    priceFormatter={(price: any) => "$" + price}

                    region="eu"

                    session= {'continue'}

                    onObjectSelected={(e: any) => onSeatSelect(e)}

                    onObjectDeselected={(e: any) => onSeatDeSelect(e)}

                />`

**Comment by mroloux** [comment]
Hi, you can get hold of the chart by implementing `onRenderStarted()`:

```
<SeatsioSeatingChart
    workspaceKey="<yourPublicWorkspaceKey>"
    event="<yourEventKey>"
    onRenderStarted={chart => { ... }}
    region="eu"
/>
```

Then you can call `chart.deselectObjects()`: https://docs.seats.io/docs/renderer/chart-properties-chartdeselectobjects/
