### ISSUE TITLE
How to selectObjects with category

### ISSUE THREAD

**Issue by PpyMohan** [seatsio/seatsio-react#98]
I have validation inside objectDeselect function. like if validation fails i need to select that deselected seats. For that i am using 
`chartObj.selectObjects([seat.id])`  after this line seat map asking to choose category.  how can i select seats with category

**Comment by bverbeken** [comment]
Closing, as this is not a seatsio-react issue. 
Feel free to reach out to seats.io support through either support@seats.io or the live support chat.
